### ISSUE TITLE
Submit 2nd edition: meta issue

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#884]
Review round 1

- [x] Part1

Review round 2: https://github.com/geocompx/geocompr/milestone/9

- [x] 10: GIS Bridges: being reviewed by @jannes-m (seems really long, should we split it?)
- [x] 12: Statistical learning, done (need minor updates)
- [x] 13: Transportation, done
- [x] 15: Ecology, more work done but basically done 

Review round 3: https://github.com/geocompx/geocompr/milestone/10

- [x] 14: Geomarketing, still needs a bit of work, will be done after ecology chapter
- [x] 9: Visualisation: waiting for tmap4 @Nowosad to lead
- [x] 11: Scripts, algorithms, functions #919 
- [x] 16: Conclusion @Robinlovelace 

Update from August 2023:

1. [x] Reread the whole book (in a source mode preferably, as there are some comments to resolve)
    - [x] Robin
    - [x] Jakub
    - [x] Jannes 
3. [x] Resolve the above mentioned comments and remove them
4. [x] Add/improve `\index`
5. [x] Add some final improvements to the last chapter
6. [x] Move tmap v4 from the separate branch to the main one (@mtennekes -- is now a good time to do it?); explain tmap v4 installation in ch2 and ch9
7. [x] Send the book for review (should we send all chapters or only the ones without previous review?)
- [x] #980
8. [x] #920 
9. [x] Look and close other GH issues
10. [x] Clean and improve acknowledgments 
11. [x] Update the "Note: Second Edition is under construction 🏗" statement

**Comment by Nowosad** [comment]
@Robinlovelace A few things we still need to do (feel free to expand the list):

1. [ ] Reread the whole book (in a source mode preferably, as there are some comments to resolve)
2. [ ] Resolve the above mentioned comments and remove them
3. [ ] Add some final improvements to the last chapter
4. [ ] Move tmap v4 from the separate branch to the main one (@mtennekes -- is now a good time to do it?); explain tmap v4 installation in ch2 and ch9
5. [ ] Send the book for review (should we send all chapters or only the ones without previous review?)
6. [ ] New book cover competition?
7. [ ] #920 
8. [ ] Clean and improve acknowledgments 
9. [ ] Update the "Note: Second Edition is under construction 🏗" statement

**Comment by Robinlovelace** [comment]
>  Send the book for review (should we send all chapters or only the ones without previous review?)

I vote send the whole book rather than new chapters only.

**Comment by Robinlovelace** [comment]
Will check with Laura now.

**Comment by Robinlovelace** [comment]
Will shift those bullet points into the original post.

**Comment by Robinlovelace** [comment]
> New competition?

Great idea, have created a new issue #980

**Comment by Robinlovelace** [comment]
Although the bar can be: the updated graphics need to be better than the previous ones (I think it's not essential to update the cover).

**Comment by Nowosad** [comment]
I think it would be nice to have a new cover.

**Comment by jannes-m** [comment]
Maybe I am wrong but I think the Geomarketing chapter has been already reviewed.

**Comment by Robinlovelace** [comment]
Submitted :tada:
